spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog
bot:
  #    username: khodir_smm_bot
  #    token: 6899467533:AAHa8OI2oHPoZp5SpQmsT76nsJNU-y3FVJA
  username: SotildiZuhrmedia_bot
  token: 6561395483:AAHaLP6JdFTWg0hupTYi1jfQfUJpbiPKH7k