#spring.datasource.url=jdbc:postgresql://localhost:5432/andqxai
server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegrambot
    username: postgres
    password: root123
  profiles:
    active: #activeProfile#
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#  config:
#    activate:
#      on-profile: spring.profiles.active@

bot:
  username: openbudget37_bot
  token: 7064767128:AAFUfF-AfB-oJsHxSHnD50BL32Luz3dSydg
#  username: SotildiZuhrmedia_bot
#  token: 6561395483:AAHaLP6JdFTWg0hupTYi1jfQfUJpbiPKH7k